# Generated by Django 4.2.5 on 2023-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='contact_logos/'),
        ),
    ]
